### ISSUE TITLE
选择太大的照片会直接报错

### ISSUE THREAD

**Issue by wkbin** [donkingliang/ImageSelector#55]
2020-04-22 11:42:29.101 7348-7348/com.pddecode.lianmodu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pddecode.lianmodu, PID: 7348
    java.lang.RuntimeException: Canvas: trying to draw too large(256872448bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at com.donkingliang.imageselector.view.ClipImageView.onDraw(ClipImageView.java:124)
        at android.view.View.draw(View.java:21473)
        at android.view.View.updateDisplayListIfDirty(View.java:20350)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
        at android.view.View.draw(View.java:21476)
        at android.view.View.updateDisplayListIfDirty(View.java:20350)
        at android.view.View.draw(View.java:21205)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)

**Comment by donkingliang** [comment]
图片剪切页面是有做图片采样压缩的，但是为了缩放后的清晰度，我用图片宽高的最小边做采样比例的计算。所以如果你的图片的比很大的话，压缩后的图片可能依然很大。

**Comment by nxnyk** [comment]
同遇到该问题，怎么解决呢
