### ISSUE TITLE
android11 miui12.1.1稳定版 拍照崩溃 参数传递异常

### ISSUE THREAD

**Issue by 710399346** [donkingliang/ImageSelector#68]
java.lang.IllegalArgumentException: Invalid token limit
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
        at android.content.ContentResolver.query(ContentResolver.java:1197)
        at android.content.ContentResolver.query(ContentResolver.java:1128)
        at android.content.ContentResolver.query(ContentResolver.java:1084)
        at com.donkingliang.imageselector.utils.ImageUtil.isNeedSavePicture(ImageUtil.java:338)
        at com.donkingliang.imageselector.utils.ImageUtil.access$000(ImageUtil.java:24)
        at com.donkingliang.imageselector.utils.ImageUtil$1.run(ImageUtil.java:321)
        at java.lang.Thread.run(Thread.java:923)

**Comment by 710399346** [comment]
打开相册 选择拍照 确定照片后进入预览图片页 发生了崩溃

**Comment by ChangKaiKing** [comment]
vivo v2024A 报错一样，好像是框架读取对应图片时文件格式出现问题，希望作者可以修复一下

**Comment by donkingliang** [comment]
我用Android 11模拟器测试是没有问题的。

我根据你们提供的log，修改了一下代码。由于我没有你们说的机型测试，所以请帮忙拉取我的demo测试一下，并给我个反馈。谢谢！
